version: '1.0'
services:
    mongodb:
        image: mongo:latest
        # environment:
        #     - name=value
        env_file:
            - ./database/.env
        ports:
            - $DB_PORT:$DB_PORT
        volumes:
            - db:/data/db
    webGate:
        build: ./webGate # build Dockerfile at this location
        depends_on:
            - mongodb # start mongo container first
        # image: webgate:latest
        environment:
            - MONGODB_CONNSTRING=mongodb://$DB_USER:$DB_PASS@$DB_HOST
        env_file:
            - ./webGate/.env
        ports:
            - $PORT:$PORT
