
services:
    mongodb:
        build: ./database
        # environment:
        #     - name=value
        env_file:
            - ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        ports:
            - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
        volumes:
            - db:/data/db
    webgate:
        build: ./webGate # build Dockerfile at this location
        depends_on:
            - mongodb # start mongo container first
        # image: webgate:latest
        environment:
            - MONGODB_CONNSTRING=mongodb://$MONGODB_USER:$MONGODB_PASSWORD@$MONGODB_HOST
        env_file:
            - ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
volumes:
    db:
